// Command genconfusables compacts Unicode's confusables.txt, vendored in
// third_party/unicode/, into internal/cli/confusables_table.go: the version,
// the source file's digest, and one line per mapping. Run it from anywhere in
// the module (go generate ./internal/cli does).
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/action-state-group/capsule-cli/internal/cli"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genconfusables:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}").Output()
	if err != nil {
		return err
	}
	dir := strings.TrimSpace(string(root))
	txt, err := os.ReadFile(filepath.Join(dir, "third_party", "unicode", "confusables.txt"))
	if err != nil {
		return err
	}
	version, table, err := cli.ConfusablesTable(txt)
	if err != nil {
		return err
	}
	sum := sha256.Sum256(txt)
	src := fmt.Sprintf(`// Code generated by scripts/genconfusables from third_party/unicode/confusables.txt. DO NOT EDIT.

package cli

// confusablesVersion is the Unicode version of the vendored confusables.txt.
const confusablesVersion = %q

// confusablesSourceSHA256 is the SHA-256 of the vendored confusables.txt.
const confusablesSourceSHA256 = %q

// confusablesTable is one line per TR39 mapping: the source and its
// prototype, as hex code points.
const confusablesTable = %s
`, version, hex.EncodeToString(sum[:]), "`"+table+"`")
	out, err := format.Source([]byte(src))
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "internal", "cli", "confusables_table.go"), out, 0o644)
}
