// Command skillgen renders a skill-spec/v0 YAML document (see
// schemas/skill-spec-v0.json and skills/SKILL-SPEC.md) into a Claude Code
// SKILL.md and a Codex AGENTS.md. The spec is the only editable source; the
// rendered files are build output regenerated by this command, never
// hand-edited — `--check` fails when a rendered file no longer matches what
// the spec renders.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"

	"github.com/santhosh-tekuri/jsonschema/v6"
	"go.yaml.in/yaml/v3"
)

// SkillMeta becomes the rendered SKILL.md frontmatter.
type SkillMeta struct {
	Name        string `yaml:"name" json:"name"`
	Description string `yaml:"description" json:"description"`
}

// Verb is one entry in the skill's action surface. EmissionMode names which
// of the three mechanisms in skills/SKILL-SPEC.md satisfies "every
// skill-driven action emits a capsule" for this verb.
type Verb struct {
	Name         string   `yaml:"name" json:"name"`
	Args         []string `yaml:"args" json:"args"`
	When         string   `yaml:"when" json:"when"`
	Emits        string   `yaml:"emits" json:"emits"`
	EmissionMode string   `yaml:"emission_mode" json:"emission_mode"`
}

// Spec is the parsed, schema-validated skill-spec/v0 document.
type Spec struct {
	SpecVersion    string    `yaml:"spec_version" json:"spec_version"`
	Skill          SkillMeta `yaml:"skill" json:"skill"`
	May            []string  `yaml:"may" json:"may"`
	MustNever      []string  `yaml:"must_never" json:"must_never"`
	ApprovalPoints []string  `yaml:"approval_points" json:"approval_points"`
	Verbs          []Verb    `yaml:"verbs" json:"verbs"`
}

// compileSchema mirrors the read pattern internal/cli/contract.go uses for
// --schema: the compiler resolves a plain filesystem path directly, no
// custom loader needed for a local, non-URL schema.
func compileSchema(path string) (*jsonschema.Schema, error) {
	compiler := jsonschema.NewCompiler()
	return compiler.Compile(path)
}

// loadSpec reads path twice by design, same as loadSchema in
// internal/cli/contract.go: once into a generic document so the compiled
// schema's additionalProperties:false actually catches a stray or misspelled
// field, and once into the typed Spec the renderer walks. A YAML mapping
// decodes into map[string]interface{} when the target is `any`, so no
// map[interface{}]interface{} conversion is needed before json.Marshal.
func loadSpec(specPath, schemaPath string) (Spec, error) {
	raw, err := os.ReadFile(specPath)
	if err != nil {
		return Spec{}, fmt.Errorf("cannot read spec %s: %w", specPath, err)
	}
	var generic any
	if err := yaml.Unmarshal(raw, &generic); err != nil {
		return Spec{}, fmt.Errorf("%s: invalid YAML: %w", specPath, err)
	}
	jsonBytes, err := json.Marshal(generic)
	if err != nil {
		return Spec{}, fmt.Errorf("%s: cannot re-encode as JSON for schema validation: %w", specPath, err)
	}
	doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(jsonBytes))
	if err != nil {
		return Spec{}, fmt.Errorf("%s: cannot decode for schema validation: %w", specPath, err)
	}
	schema, err := compileSchema(schemaPath)
	if err != nil {
		return Spec{}, fmt.Errorf("cannot load --schema %s: %w", schemaPath, err)
	}
	if err := schema.Validate(doc); err != nil {
		return Spec{}, fmt.Errorf("%s does not satisfy %s: %w", specPath, schemaPath, err)
	}
	var spec Spec
	if err := yaml.Unmarshal(raw, &spec); err != nil {
		return Spec{}, fmt.Errorf("%s: %w", specPath, err)
	}
	if len(spec.Verbs) == 0 {
		return Spec{}, errors.New("spec passed schema validation but decoded zero verbs; schema and struct tags have drifted")
	}
	return spec, nil
}
