package cli

import (
	"bytes"
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"errors"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/emersion/go-msgauth/dkim"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The merchant fixtures are SYNTHETIC: a made-up shop on a reserved domain
// (shop.example), a made-up customer, signed with a throwaway RSA-2048 key
// generated by TestRegenerateMerchantEmailFixtures. Only the public half is
// kept, as the TXT record; the private key is discarded after signing.
const merchantFixture = "testdata/deal/merchant-email"

const merchantSelector = "s2026"

var merchantEmails = []struct{ file, order, date, total string }{
	{"confirmation.eml", "SE-104233", "Sat, 03 Oct 2026 21:14:05 +0000", "64.00"},
	{"confirmation-2.eml", "SE-104251", "Sat, 03 Oct 2026 21:16:40 +0000", "64.00"},
}

func merchantMessage(order, date, total string) string {
	plain := strings.Join([]string{
		"Thanks for your order!",
		"",
		"Order number: " + order,
		"",
		"Sticker pack (3 designs)   Qty: 1   $58.00",
		"",
		"Subtotal: $58.00",
		"Shipping: $6.00",
		"Order total: $" + total,
		"",
		"Changed your mind? You can cancel this order until October 10, 2026",
		"from your account page.",
		"",
		"Shop Example",
	}, "\r\n")
	html := `<html><body><p>Thanks for your order!</p><table><tr><td>Order number</td><td>` + order +
		`</td></tr><tr><td>Order total</td><td>$` + total + `</td></tr></table></body></html>`
	return strings.Join([]string{
		"From: Shop Example <orders@shop.example>",
		"To: Sam Customer <sam.customer@mail.example>",
		"Subject: Your Shop Example order " + order + " is confirmed",
		"Date: " + date,
		"Message-ID: <" + strings.ToLower(order) + "@shop.example>",
		"MIME-Version: 1.0",
		`Content-Type: multipart/alternative; boundary="b1"`,
		"",
		"--b1",
		"Content-Type: text/plain; charset=utf-8",
		"Content-Transfer-Encoding: 7bit",
		"",
		plain,
		"--b1",
		"Content-Type: text/html; charset=utf-8",
		"Content-Transfer-Encoding: 7bit",
		"",
		html,
		"--b1--",
		"",
	}, "\r\n")
}

// TestRegenerateMerchantEmailFixtures rewrites the signed fixtures with a new
// throwaway key. It runs only when asked:
//
//	CAPSULECTL_REGEN_MERCHANT_EMAIL=1 go test ./internal/cli -run TestRegenerateMerchantEmailFixtures
func TestRegenerateMerchantEmailFixtures(t *testing.T) {
	if os.Getenv("CAPSULECTL_REGEN_MERCHANT_EMAIL") == "" {
		t.Skip("set CAPSULECTL_REGEN_MERCHANT_EMAIL=1 to regenerate the signed fixtures")
	}
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	require.NoError(t, err)
	for _, m := range merchantEmails {
		var signed bytes.Buffer
		err := dkim.Sign(&signed, strings.NewReader(merchantMessage(m.order, m.date, m.total)), &dkim.SignOptions{
			Domain: "shop.example", Selector: merchantSelector, Signer: key, Hash: crypto.SHA256,
			HeaderCanonicalization: dkim.CanonicalizationRelaxed, BodyCanonicalization: dkim.CanonicalizationRelaxed,
			HeaderKeys: []string{"From", "To", "Subject", "Date", "Message-ID", "MIME-Version", "Content-Type"},
		})
		require.NoError(t, err)
		require.NoError(t, os.WriteFile(filepath.Join(merchantFixture, m.file), signed.Bytes(), 0o644))
	}
	der, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	require.NoError(t, err)
	record := merchantSelector + `._domainkey.shop.example. 3600 IN TXT "v=DKIM1; k=rsa; p=` + base64.StdEncoding.EncodeToString(der) + `"` + "\n"
	require.NoError(t, os.WriteFile(filepath.Join(merchantFixture, "key-record.txt"), []byte(record), 0o644))
	// dmarc-record.txt (the shop's p=reject policy) holds no key and is not regenerated.
}

const dmarcName = "_dmarc.shop.example"

func merchantDMARC(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(merchantFixture, "dmarc-record.txt"))
	require.NoError(t, err)
	recs, err := parseDMARCRecord(b, "shop.example")
	require.NoError(t, err)
	require.Equal(t, dmarcName, recs[0].Name)
	return recs[0].TXT[0]
}

func merchantKeyTXT(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(merchantFixture, "key-record.txt"))
	require.NoError(t, err)
	keys, err := parseKeyRecord(b, nil)
	require.NoError(t, err)
	require.Equal(t, merchantSelector+"._domainkey.shop.example", keys[0].Name)
	return keys[0].TXT[0]
}

// stubDNS answers key lookups as the merchant's DNS would at seal time, and
// returns a restore function that makes any further lookup fail the test.
func stubDNS(t *testing.T, records map[string]string) func() {
	t.Helper()
	old := dkimLookup
	dkimLookup = func(name string) ([]string, error) {
		if txt, ok := records[name]; ok {
			return []string{txt}, nil
		}
		return nil, &net.DNSError{Err: "no such host", Name: name, IsNotFound: true}
	}
	t.Cleanup(func() { dkimLookup = old })
	return func() {
		dkimLookup = func(name string) ([]string, error) {
			t.Errorf("network lookup during offline verification: %s", name)
			return nil, errors.New("offline")
		}
	}
}

func openMerchantDeal(t *testing.T) (dealID string) {
	t.Helper()
	dealID = dealRun(t, "open", "--input", writeJSON(t, `{
		"type": "purchase", "channel": "web",
		"intent": {"verbatim": "Buy the 3-design sticker pack from Shop Example, no more than $50 all in", "max_total_minor": 5000, "allowed": ["pay"]},
		"who": {"name": "Shop Example", "domain": "shop.example"},
		"terms": {"item": "sticker pack", "quantity": 1, "price_minor": 4800, "currency": "USD"},
		"recourse": {"rail": "card", "refundable": true}
	}`))["deal_id"].(string)
	check := dealRun(t, "check", "--deal", dealID, "--input", writeJSON(t, `{"action":"pay","amount_minor":4800,"description":"pay for the sticker pack"}`))
	require.Equal(t, "pass", check["verdict"], check["card"])
	paid := dealRun(t, "note", "--deal", dealID, "--kind", "act", "--input", writeJSON(t, `{"action":"pay","amount_minor":4800,"rail":"card","reference":"card ending 4242 auth 99812"}`))
	require.Equal(t, false, paid["unchecked"])
	return dealID
}

// The acceptance run: a merchant confirmation is sealed on a deal with its key
// record; it verifies offline against the sealed key; an altered copy fails;
// the report sets approved beside charged; and the receipt keeps the
// merchant's attestation and our seal apart, in plain words.
func TestDealMerchantEmailSealVerifyAndMismatch(t *testing.T) {
	dealFixture(t)
	offline := stubDNS(t, map[string]string{merchantSelector + "._domainkey.shop.example": merchantKeyTXT(t), dmarcName: merchantDMARC(t)})
	dealID := openMerchantDeal(t)

	email := filepath.Join(merchantFixture, "confirmation.eml")
	sealed := dealRun(t, "note", "--deal", dealID, "--kind", "evidence", "--email", email)
	assert.Equal(t, "pass", sealed["dkim"])
	assert.Equal(t, true, sealed["merchant_signed"])
	assert.Equal(t, "dns", sealed["key_source"])
	assert.Equal(t, "signed", sealed["checkpoint"].(map[string]any)["state"], "the key record is checkpointed at once")
	assert.Contains(t, sealed["merchant_says"], "shop.example sent this email")
	assert.True(t, strings.HasPrefix(sealed["merchant_says"].(string), "merchant-confirmed: "))
	assert.Equal(t, "reject", sealed["dmarc_policy"])
	assert.Contains(t, sealed["we_say"], "our own record")
	assert.Equal(t, emailScopeLine, sealed["scope"], "the email result states its own scope")
	parsed := sealed["parsed"].(map[string]any)
	assert.Equal(t, "SE-104233", parsed["order_id"])
	assert.Equal(t, "order", parsed["order_id_label"])
	assert.Equal(t, float64(6400), parsed["total_minor"], "the order total, not the subtotal")
	assert.Equal(t, "USD", parsed["currency"])
	assert.Equal(t, "2026-10-10", parsed["cancel_by"])
	assert.Equal(t, "2026-10-03T21:14:05Z", parsed["sent_at"])

	// A second order for the same amount: a likely duplicate charge.
	dealRun(t, "note", "--deal", dealID, "--kind", "evidence", "--email", filepath.Join(merchantFixture, "confirmation-2.eml"))

	// From here on there is no network: any DNS lookup fails the test.
	offline()
	v := dealRun(t, "verify-email", "--deal", dealID)
	assert.Equal(t, true, v["verified"])
	assert.Equal(t, emailScopeLine, v["scope"])
	assert.Len(t, v["emails"], 2)
	got := v["emails"].([]any)[0].(map[string]any)
	assert.Equal(t, "pass", got["dkim"])
	assert.Contains(t, got["network"], "not used")

	// A deliberately altered copy: one amount changed in the body.
	raw, err := os.ReadFile(email)
	require.NoError(t, err)
	altered := bytes.Replace(raw, []byte("Order total: $64.00"), []byte("Order total: $48.00"), 1)
	require.NotEqual(t, raw, altered)
	alteredPath := filepath.Join(t.TempDir(), "altered.eml")
	require.NoError(t, os.WriteFile(alteredPath, altered, 0o600))
	out, err := invoke(t, "", "--profile", "deal", "deal", "verify-email", "--deal", dealID, "--step", strconv.Itoa(int(sealed["step"].(float64))), "--email", alteredPath)
	require.ErrorIs(t, err, ErrEmailUnverified)
	assert.Equal(t, 1, ExitCode(err))
	var bad map[string]any
	require.NoError(t, json.Unmarshal([]byte(out), &bad), out)
	assert.Equal(t, false, bad["verified"])
	b0 := bad["emails"].([]any)[0].(map[string]any)
	assert.Equal(t, false, b0["copy_is_sealed_message"])
	assert.Equal(t, "fail", b0["dkim"])
	assert.Contains(t, b0["merchant_says"], "not confirmed: fails DMARC alignment (domain policy p=reject); the signature does not check out")

	page := filepath.Join(t.TempDir(), "receipt.html")
	receipt := filepath.Join(t.TempDir(), "receipt.eml")
	report := dealRun(t, "report", "--deal", dealID, "--html", page, "--email", receipt)
	rows := report["merchant"].([]any)
	require.Len(t, rows, 2)
	row := rows[0].(map[string]any)
	assert.Equal(t, "$48.00", row["approved"])
	assert.Equal(t, "the amount checked against what you already allowed", row["approved_basis"])
	assert.Equal(t, "$64.00", row["charged"])
	assert.Equal(t, "2026-10-03", row["charged_on"])
	assert.Equal(t, "2026-10-10", row["cancel_by"])
	assert.Equal(t, true, row["verified"])
	assert.NotEqual(t, row["merchant_says"], row["we_say"])
	assert.Equal(t, "RSA 2048-bit", row["key_size"])
	assert.Equal(t, "shop.example", row["signing_domain"])
	assert.Equal(t, "shop.example", row["merchant_apex"])
	assert.Equal(t, "signed by shop.example, the merchant's own domain (apex shop.example)", row["domains"])

	// The receipt email carries the same comparison, in the same words, in
	// both its plain-text and HTML bodies, under the email's own scope line.
	mail := report["email"].(map[string]any)
	for _, body := range []string{mail["text"].(string), mail["html"].(string)} {
		body = strings.ReplaceAll(body, "&#39;", "'")
		for _, want := range []string{
			dealScopeLine, emailScopeLine, "The merchant's own email",
			"Merchant's signature: " + row["merchant_says"].(string), "Our seal: " + ourSealWords,
			"You approved (the amount checked against what you already allowed)", "$48.00",
			"The merchant's email says (read from the email)", "$64.00", "2026-10-10",
			"signed by shop.example, the merchant's own domain (apex shop.example)", "RSA 2048-bit, sealed when the email was sealed",
		} {
			assert.Contains(t, body, want)
		}
		assert.NotContains(t, strings.ToLower(body), "bilateral")
	}
	eml, err := os.ReadFile(receipt)
	require.NoError(t, err)
	assert.Contains(t, string(eml), "Content-Type: multipart/mixed")

	kinds := map[string]string{}
	for _, a := range report["anomalies"].([]any) {
		a := a.(map[string]any)
		kinds[a["kind"].(string)] = a["text"].(string)
	}
	assert.Equal(t, "Approved $48.00; the merchant's email says $64.00", kinds["charged_differs"])
	assert.Equal(t, "Possible duplicate charge: the merchant's emails show $64.00 twice (orders SE-104233 and SE-104251)", kinds["duplicate_charge"])
	assert.NotContains(t, kinds, "charged_before_cancel_by", "a retail cancel window is not a trial: charging at order time is expected")

	assert.Equal(t, dealScopeLine, report["scope"])
	assert.Contains(t, report["did_line"], "with an independent source attached: the merchant's own email, its signature checked against the merchant's key sealed at ")
	html, err := os.ReadFile(page)
	require.NoError(t, err)
	assert.Contains(t, string(html), "Merchant's signature: ")
	assert.Contains(t, string(html), "Our seal: ")
	b := embeddedBundle(t, string(html))
	deal := b["extensions"].(map[string]interface{})["x-deal-v0"].(map[string]interface{})
	assert.Contains(t, string(html), dealScopeLine, "the receipt states its scope on its face")
	assert.Contains(t, deal["did_line"], "independent source attached")
	assert.Equal(t, emailScopeLine, deal["email_scope"])
	ext, err := json.Marshal(b["extensions"])
	require.NoError(t, err)
	for _, never := range []string{"all activity", "complete history", "complete record"} {
		assert.NotContains(t, strings.ToLower(string(ext)), never, "never imply completeness")
	}
	for _, ours := range []string{string(ext), dealViewJS} {
		assert.NotContains(t, strings.ToLower(ours), "bilateral", "never one combined attestation badge")
	}
	disclosed, err := json.Marshal(b["disclosures"])
	require.NoError(t, err)
	for _, private := range []string{"sam.customer@mail.example", "Sam Customer", "SE-104233", "Sticker pack (3 designs)", "DKIM-Signature"} {
		assert.NotContains(t, string(disclosed), private, "the sealed records carry digests, not the email")
	}
	assert.Contains(t, string(disclosed), emailDigest(raw), "the record names the exact bytes by digest")

	// The sealed records validate against the profile and carry no raw values.
	export := filepath.Join(t.TempDir(), "deal.json")
	dealRun(t, "export", "--deal", dealID, "--output", export)
	records, err := os.ReadFile(export)
	require.NoError(t, err)
	for _, private := range []string{"sam.customer@mail.example", "SE-104233", "shop.example", "Sticker pack"} {
		assert.NotContains(t, string(records), private)
	}
	assert.Contains(t, string(records), `"merchant_email":{"dkim":"pass","dmarc_policy":"reject","dmarc_record_digest":`)
	if python, err := exec.LookPath("python3"); err == nil {
		result, err := exec.Command(python, dealProfileDir+"/check_profile.py", export).CombinedOutput()
		require.NoError(t, err, string(result))
		assert.Contains(t, string(result), "ALL OK")
	}
}

// A sealed copy that does not verify is sealed as what it is: evidence that
// is not confirmed by the merchant. A supplied key is marked as supplied.
func TestDealMerchantEmailAlteredSuppliedKey(t *testing.T) {
	dealFixture(t)
	stubDNS(t, nil)()
	dealID := openMerchantDeal(t)
	raw, err := os.ReadFile(filepath.Join(merchantFixture, "confirmation.eml"))
	require.NoError(t, err)
	altered := filepath.Join(t.TempDir(), "altered.eml")
	require.NoError(t, os.WriteFile(altered, bytes.Replace(raw, []byte("$64.00"), []byte("$48.00"), 1), 0o600))
	sealed := dealRun(t, "note", "--deal", dealID, "--kind", "evidence", "--email", altered, "--key-record", filepath.Join(merchantFixture, "key-record.txt"))
	assert.Equal(t, "fail", sealed["dkim"])
	assert.Equal(t, "supplied", sealed["key_source"])
	assert.Equal(t, false, sealed["merchant_signed"])
	assert.Equal(t, "not_captured", sealed["dmarc_policy"])
	assert.True(t, strings.HasPrefix(sealed["merchant_says"].(string), "not confirmed: fails DMARC alignment (domain policy not captured)"))
	// With the DMARC record supplied too, its policy is shown.
	withDMARC := dealRun(t, "note", "--deal", dealID, "--kind", "evidence", "--email", altered, "--key-record", filepath.Join(merchantFixture, "key-record.txt"), "--dmarc-record", filepath.Join(merchantFixture, "dmarc-record.txt"))
	assert.Equal(t, "reject", withDMARC["dmarc_policy"])
	_, err = invoke(t, "", "--profile", "deal", "deal", "note", "--deal", dealID, "--kind", "evidence", "--email", altered, "--dmarc-record", filepath.Join(merchantFixture, "dmarc-record.txt"))
	require.ErrorIs(t, err, ErrInput, "--dmarc-record needs --key-record")
	_, err = invoke(t, "", "--profile", "deal", "deal", "verify-email", "--deal", dealID)
	require.ErrorIs(t, err, ErrEmailUnverified)
	report := dealRun(t, "report", "--deal", dealID)
	assert.Equal(t, dealScopeLine, report["scope"])
	assert.Contains(t, report["did_line"], "no independent source", "an email that is not confirmed is not a source")
	row := report["merchant"].([]any)[0].(map[string]any)
	assert.Equal(t, false, row["verified"])
	assert.Equal(t, "supplied", row["key_source"])

	// --email only goes with evidence; a key record alone is refused.
	_, err = invoke(t, "", "--profile", "deal", "deal", "note", "--deal", dealID, "--kind", "message", "--email", altered)
	require.ErrorIs(t, err, ErrInput)
	_, err = invoke(t, "", "--profile", "deal", "deal", "note", "--deal", dealID, "--kind", "evidence", "--key-record", altered)
	require.ErrorIs(t, err, ErrInput)
}

// A rotated or revoked key after sealing does not matter: verification uses
// the sealed record. A key that was never published fails.
func TestMerchantEmailKeyRotation(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(merchantFixture, "confirmation.eml"))
	require.NoError(t, err)
	name := merchantSelector + "._domainkey.shop.example"
	stubDNS(t, map[string]string{name: merchantKeyTXT(t)})
	m, err := captureEmail(raw, nil)
	require.NoError(t, err)
	require.Equal(t, "pass", m.DKIM.Result)
	stubDNS(t, map[string]string{name: "v=DKIM1; p="}) // revoked today
	v, err := m.recheck(raw)
	require.NoError(t, err)
	assert.Equal(t, "pass", v.Result, "the key as it stood at seal time still verifies")
	revoked, err := captureEmail(raw, nil)
	require.NoError(t, err)
	assert.Equal(t, "fail", revoked.DKIM.Result, "sealed only after the key was revoked: unverifiable")
	assert.Contains(t, emailVerdictWords(revoked.DKIM), "key revoked")
}

func TestParseMerchantEmailHeuristics(t *testing.T) {
	msg := strings.Join([]string{
		"From: Billing <billing@stream.example>",
		"Subject: =?utf-8?q?Your_free_trial_has_started?=",
		"Date: Thu, 01 Oct 2026 08:00:00 -0700",
		"Content-Type: text/html; charset=utf-8",
		"Content-Transfer-Encoding: quoted-printable",
		"",
		"<p>Confirmation #TR-55120</p><p>Your free trial ends soon. Cancel before October 8, 2026 =",
		"to avoid being charged.</p><table><tr><td>Subtotal</td><td>$9.00</td></tr>",
		"<tr><td>Total</td><td>&euro;12.50</td></tr></table>",
		"",
	}, "\r\n")
	p := parseMerchantEmail([]byte(msg))
	assert.Equal(t, "TR-55120", p.OrderID)
	assert.Equal(t, "confirmation", p.OrderIDLabel)
	require.NotNil(t, p.TotalMinor)
	assert.Equal(t, int64(1250), *p.TotalMinor)
	assert.Equal(t, "EUR", p.Currency)
	assert.Equal(t, "2026-10-08", p.CancelBy)
	assert.True(t, p.ChargeAfterCancelBy)
	assert.Equal(t, "2026-10-01T15:00:00Z", p.SentAt)
	assert.Equal(t, "Your free trial has started", p.Subject)

	// No signature at all: only our own seal stands behind it.
	v, err := verifyDKIM([]byte(msg), sealedLookup(nil), &dmarcCapture{Source: "dns", Records: []dkimKeyRecord{}})
	require.NoError(t, err)
	assert.Equal(t, "none", v.Result)
	assert.Equal(t, "absent", v.Policy)
	assert.Equal(t, "not confirmed: fails DMARC alignment (the domain publishes no DMARC policy); the email carries no signature, so only our own seal stands behind it", emailVerdictWords(v))
}

func TestParseKeyRecordForms(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(merchantFixture, "confirmation.eml"))
	require.NoError(t, err)
	txt := merchantKeyTXT(t)
	bare, err := parseKeyRecord([]byte(txt), raw)
	require.NoError(t, err)
	assert.Equal(t, merchantSelector+"._domainkey.shop.example", bare[0].Name, "named from the email's signature")
	_, err = parseKeyRecord([]byte("not a key"), raw)
	require.ErrorIs(t, err, ErrInput)
}

// Only an "order"-labelled id from a merchant email that checks out, signed by
// the deal's own counterparty, may be shared; booking, confirmation and
// PNR-style codes never are.
func TestShareableOrderID(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(merchantFixture, "confirmation.eml"))
	require.NoError(t, err)
	keys, err := parseKeyRecord([]byte(merchantKeyTXT(t)), raw)
	require.NoError(t, err)
	m, err := captureEmail(raw, keys)
	require.NoError(t, err)
	shop := dealWho{Name: "Shop Example", Domain: "shop.example"}
	assert.Equal(t, "SE-104233", m.shareableOrderID(shop))
	assert.Empty(t, m.shareableOrderID(dealWho{Domain: "other.example"}), "signed by someone other than the counterparty")
	assert.Empty(t, m.shareableOrderID(dealWho{Name: "Shop Example"}), "the counterparty's domain is unknown")

	altered, err := captureEmail(bytes.Replace(raw, []byte("$64.00"), []byte("$48.00"), 1), keys)
	require.NoError(t, err)
	assert.Empty(t, altered.shareableOrderID(shop), "an email that does not check out shares nothing")

	for _, label := range []string{"booking", "confirmation", "reservation", "pnr", "record locator"} {
		c := *m
		c.Parsed.OrderIDLabel = label
		assert.Empty(t, c.shareableOrderID(shop), label)
	}
	for text, label := range map[string]string{
		"Booking reference: QX7Z2K9": "booking",
		"Your PNR: ABC123":           "pnr",
		"Reservation #RV-88213":      "reservation",
		"Order #1009-2231":           "order",
		"Record locator: KD4LW2":     "record locator",
	} {
		p := parseMerchantEmail([]byte("Subject: x\r\n\r\n" + text + "\r\n"))
		assert.Equal(t, label, p.OrderIDLabel, text)
	}
}

// DMARC never decides what is sealed: a message that fails alignment is
// still evidence the user received it. It is sealed under every policy and
// marked not confirmed with the policy shown; only a passing, aligned
// signature verified by our own offline check reads as merchant-confirmed.
func TestMerchantEmailDMARCPolicies(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(merchantFixture, "confirmation.eml"))
	require.NoError(t, err)
	altered := bytes.Replace(raw, []byte("$64.00"), []byte("$48.00"), 1)
	key := merchantSelector + "._domainkey.shop.example"
	for _, tc := range []struct {
		name, dmarc, policy string
		msg                 []byte
		confirmed           bool
	}{
		{"pass", merchantDMARC(t), "reject", raw, true},
		{"fail under reject", merchantDMARC(t), "reject", altered, false},
		{"fail under quarantine", "v=DMARC1; p=quarantine", "quarantine", altered, false},
		{"fail under none", "v=DMARC1; p=none", "none", altered, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			offline := stubDNS(t, map[string]string{key: merchantKeyTXT(t), dmarcName: tc.dmarc})
			m, err := captureEmail(tc.msg, nil)
			require.NoError(t, err, "never refused to seal, whatever the policy")
			assert.Equal(t, "dns", m.DMARC.Source)
			assert.Equal(t, tc.policy, m.DKIM.Policy)
			offline()
			v, err := m.recheck(tc.msg)
			require.NoError(t, err)
			assert.Equal(t, tc.policy, v.Policy, "the policy comes from the sealed record, offline")
			words := emailVerdictWords(v)
			if tc.confirmed {
				assert.True(t, strings.HasPrefix(words, "merchant-confirmed: "), words)
				return
			}
			assert.True(t, strings.HasPrefix(words, "not confirmed: fails DMARC alignment (domain policy p="+tc.policy+")"), words)
			assert.NotContains(t, words, "merchant-confirmed")
		})
	}

	// A passing signature that is not aligned (a mailing service's domain)
	// is not confirmed either; adkim=s makes a parent domain unaligned.
	assert.False(t, dmarcAligned("shop.example", "mailer.example", false))
	assert.True(t, dmarcAligned("mail.shop.example", "shop.example", false))
	assert.False(t, dmarcAligned("mail.shop.example", "shop.example", true))
	assert.True(t, dmarcAligned("shop.co.uk", "mail.shop.co.uk", false))
	assert.False(t, dmarcAligned("a.co.uk", "b.co.uk", false), "the public suffix is not an organization")
	v := merchantEmailVerdict{Result: "pass", FromDomain: "shop.example", Policy: "reject", Signatures: []dealSignature{{Domain: "mailer.example", Result: "pass"}}}
	assert.Equal(t, "not confirmed: fails DMARC alignment (domain policy p=reject); signed by mailer.example, which is not the sender's own domain (shop.example): this shows who relayed it, not that the merchant sent it", emailVerdictWords(v))

	// A subdomain sender with no record of its own takes the organizational
	// domain's sp=.
	pol := dmarcPolicyOf("mail.shop.example", &dmarcCapture{Source: "dns", Records: []dkimKeyRecord{
		{Name: "_dmarc.mail.shop.example"}, {Name: dmarcName, TXT: []string{"v=DMARC1; p=reject; sp=quarantine"}},
	}})
	assert.Equal(t, "quarantine", pol.policy)
}

func TestMerchantDomainWords(t *testing.T) {
	assert.Equal(t, "signed by mail.shop.example, the merchant's own domain (apex shop.example)", domainWords("mail.shop.example", "shop.example"))
	assert.Equal(t, "signed by mailer.example; the merchant's domain (apex) is shop.example: not the same organization", domainWords("mailer.example", "shop.example"))
	assert.Equal(t, "no signature passed; the merchant's domain (apex) is shop.example", domainWords("", "shop.example"))
}
